name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
        working-directory: ./knihobot_test
      - name: Run tests
        run: npm test
        working-directory: ./knihobot_test
      - name: Build app
        run: npm run build
        working-directory: ./knihobot_test
      - name: Build Docker image
        run: docker build -t knihobot-test ./knihobot_test 